sudo: required
services:
  - docker

before_install:
  - docker build -t jamespsteinberg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jamespsteinberg/react-test npm test -- --coverage

after_success:
  - docker build -t jamespsteinberg/multiclient ./client
  - docker build -t jamespsteinberg/multinginx ./nginx
  - docker build -t jamespsteinberg/multiserver ./server
  - docker build -t jamespsteinberg/multiworker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jamespsteinberg/multiclient
  - docker push jamespsteinberg/multinginx
  - docker push jamespsteinberg/multiserver
  - docker push jamespsteinberg/multiworker
