sudo: required
services:
  - docker

before_install:
  - docker build -t jamespsteinberg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jamespsteinberg/react-test npm test -- --coverage

after_success:
  - docker build -t jamespsteinberg/multiclient ./client
  - docker build -t jamespsteinberg/multinginx ./nginx
  - docker build -t jamespsteinberg/multiserver ./server
  - docker build -t jamespsteinberg/multiworker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jamespsteinberg/multiclient
  - docker push jamespsteinberg/multinginx
  - docker push jamespsteinberg/multiserver
  - docker push jamespsteinberg/multiworker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multidocker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-365338374368
  bucket_path: multidocker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
